### ISSUE TITLE
Build on Jan 10 2015 did not run on R-Pi

### ISSUE THREAD

**Issue by otembajelle** [wimjongman/pipolos#2]
Thank you for starting Pipolos. A very smart IOT use case example and very useful as a smart OSGi runtime for the R-Pi. Please continue with Pipolos!

I build Pipolos on last Saturday on the Pi (Windows also) and failed to get it running. I use a recent NOOBS on a Pi A+ and B+. It will not come as a surprise that there is no different result for building on Linux or Windows nor the A+ vs B+ platform.

I closely followed the instructions.

OSGi starts all right. Very few of Wim's bundels get to an active state. A representative part of the stacktrace is originated by the loading of the Felix Web-Console bundle:

"Caused by: java.lang.ClassNotFoundException: org.apache.felix.webconsole.internal.OsgiManagerActivator cannot be found by org.apache.felix.webconsole_4.2.2.all
at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:432)"

ECF as far as I could see using the "ss"-command, the ECF's bundles did not start as well. Apart from the other part of the stacktrace, I have no other info other than a lot of bundles that do not show or stay in a resolved state.

**Comment by wimjongman** [comment]
Hi Jelle,

Thanks for reporting. It think your runtime is ok. Other than Felix, bundles in equinox do not by default autostart. Also, it is not required that they do. 

If you get the console prompt then you have a working pipolos.

There is no need to manually start bundles. Did you actually try to open the web console by following the instructions on the home page of pipolos?

If you are going to use ECF, then the distribution bundle is the one that sets ECF in motion. Please let me know what you plan to do so that we can be more specific.

**Comment by otembajelle** [comment]
Thx for your reply. The Felix Web Console is not accessible, which makes sense based on the Exception above. Jetty is ok and responds instead. So based on your reply, I misinterpretated the state of the bundles indeed. It might not be a big problem after all, if the Web Console is fixed.

----- Ursprüngliche Nachricht -----
Von: "Wim Jongman" <notifications@github.com>
Gesendet: ‎13.‎01.‎2015 13:17
An: "wimjongman/pipolos" <pipolos@noreply.github.com>
Cc: "otembajelle" <jelleVanWieringen@yahoo.com>
Betreff: Re: [pipolos] Build on Jan 10 2015 did not run on R-Pi (#2)

Hi Jelle,
Thanks for reporting. It think your runtime is ok. Other than Felix, bundles in equinox do not by default autostart. Also, it is not required that they do. 
If you get the console prompt then you have a working pipolos.
There is no need to manually start bundles. Did you actually try to open the web console by following the instructions on the home page of pipolos?
If you are going to use ECF, then the distribution bundle is the one that sets ECF in motion. Please let me know what you plan to do so that we can be more specific.

**Comment by drystone** [comment]
I think I have a fix for this. *.class found it's way into some .gitignore files, causing the webconsole's class files to disappear from the repo. Thus a clean checkout is missing these files. Your working dir, Wim, probably still has them so you don't see the bug.

I've made a pull request.

Cheers

**Comment by wimjongman** [comment]
Right! Thanks for spotting this. I think we should reference webconsole from a repo instead of hosting the binaries here.

I have pulled your changes. @otembajelle can you try again?

**Comment by otembajelle** [comment]
Thanks to John and Wim. Pipolos builds and works flawless on my Pies.
